// OpenAI client configuration
// This file sets up the connection to OpenAI for AI content generation

import OpenAI from 'openai';

// Get OpenAI API key from environment variables
const apiKey = process.env.OPENAI_API_KEY;

// Check if API key is set
if (!apiKey) {
  console.warn('Warning: OpenAI API key is not set. AI features will not work.');
}

/**
 * Create an OpenAI client instance
 * This client is used to interact with OpenAI's API
 */
export const openai = new OpenAI({
  apiKey: apiKey || '',
});

/**
 * Generate marketing content for a real estate property using AI
 * @param propertyInfo - Information about the property
 * @returns AI-generated marketing content
 */
export async function generatePropertyContent(propertyInfo: {
  address?: string;
  propertyType?: string;
  bedrooms?: number;
  bathrooms?: number;
  squareFeet?: number;
  price?: number;
  features?: string[];
}) {
  try {
    // Create a detailed prompt for the AI
    const prompt = `Generate compelling marketing content for a real estate property with the following details:
    
Address: ${propertyInfo.address || 'Not specified'}
Property Type: ${propertyInfo.propertyType || 'Not specified'}
Bedrooms: ${propertyInfo.bedrooms || 'Not specified'}
Bathrooms: ${propertyInfo.bathrooms || 'Not specified'}
Square Feet: ${propertyInfo.squareFeet || 'Not specified'}
Price: ${propertyInfo.price ? `$${propertyInfo.price.toLocaleString()}` : 'Not specified'}
Features: ${propertyInfo.features?.join(', ') || 'Not specified'}

Please generate:
1. A catchy headline (max 10 words)
2. A detailed property description (150-200 words)
3. 5 key features as bullet points
4. A short Instagram caption (max 150 characters)
5. A Facebook post (max 300 characters)

Format the response as JSON with keys: headline, description, keyFeatures (array), instagram, facebook`;

    // Call OpenAI's chat completion API
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o', // Using latest GPT-4o model
      messages: [
        {
          role: 'system',
          content: 'You are a professional real estate copywriter who creates engaging, persuasive marketing content.',
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.8, // Higher temperature for more creative output
    });

    // Parse the AI response
    const content = completion.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No content generated by AI');
    }

    const result = JSON.parse(content);
    return {
      success: true,
      data: result,
    };
  } catch (error: any) {
    console.error('OpenAI error:', error.message);
    return {
      success: false,
      error: error.message || 'Failed to generate content',
    };
  }
}

/**
 * Analyze property images using OpenAI's vision capabilities
 * Enhanced version that identifies room types and specific features
 * @param imageUrl - URL of the image to analyze
 * @returns Detailed analysis of the image
 */
export async function analyzePropertyImage(imageUrl: string) {
  try {
    // Call OpenAI's vision API with enhanced prompt
    const response = await openai.chat.completions.create({
      model: 'gpt-4o', // Using GPT-4o which has vision capabilities
      messages: [
        {
          role: 'system',
          content: 'You are a professional real estate photographer and marketing expert. Analyze property images and identify key features that would appeal to buyers.',
        },
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `Analyze this property image in detail. Focus ONLY on PERMANENT features of the property.

IDENTIFY:
1. Room/Area Type (kitchen, bedroom, bathroom, living room, living_room, outdoor, exterior, etc.)
2. PERMANENT Features ONLY: appliances, finishes, flooring, countertops, fixtures, cabinetry, architectural elements, landscaping
3. Quality/Style Description (modern, luxury, traditional, contemporary, etc.)
4. Key Selling Points (what makes this space special)

DO NOT INCLUDE:
- Furniture (sofas, chairs, tables, beds, dressers)
- Staging items (decorative objects, artwork, lamps, rugs, pillows)
- Temporary items (plants in pots, personal items)

FOCUS ON:
- Built-in features and appliances
- Materials and finishes (wood, marble, granite, tile)
- Architectural details (moldings, ceilings, windows)
- Permanent fixtures (lighting fixtures, faucets, hardware)
- Landscaping and outdoor permanent features

Return ONLY valid JSON with this exact structure:
{
  "roomType": "kitchen",
  "features": ["stainless steel appliances", "granite countertops", "custom white cabinetry"],
  "styleDescription": "modern contemporary",
  "sellingPoints": ["professional-grade kitchen", "abundant natural light"]
}`,
            },
            {
              type: 'image_url',
              image_url: {
                url: imageUrl,
                detail: 'high',
              },
            },
          ],
        },
      ],
      max_tokens: 500,
      response_format: { type: 'json_object' },
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No analysis generated by AI');
    }

    return {
      success: true,
      data: JSON.parse(content),
    };
  } catch (error: any) {
    console.error('Image analysis error:', error.message);
    return {
      success: false,
      error: error.message || 'Failed to analyze image',
    };
  }
}

/**
 * Analyze multiple property images in batch
 * @param images - Array of image URLs (strings) or image objects with url property
 * @returns Array of analysis results organized by room type
 */
export async function analyzePropertyImages(images: Array<string | { url: string; id?: string; caption?: string }>) {
  try {
    const analyses = [];
    
    // Analyze each image (note: in production, consider rate limiting)
    for (let i = 0; i < images.length; i++) {
      const image = images[i];
      
      // Handle both string URLs and object format
      const imageUrl = typeof image === 'string' ? image : image.url;
      const imageId = typeof image === 'string' ? `image-${i}` : (image.id || `image-${i}`);
      
      // Skip empty or invalid URLs
      if (!imageUrl || imageUrl.trim() === '') {
        console.warn(`Skipping empty image URL at index ${i}`);
        continue;
      }
      
      const result = await analyzePropertyImage(imageUrl);
      if (result.success && result.data) {
        analyses.push({
          imageId,
          imageUrl,
          ...result.data,
        });
      }
    }
    
    // Organize by room type
    const byRoomType: Record<string, any[]> = {};
    analyses.forEach(analysis => {
      const roomType = analysis.roomType || 'general';
      if (!byRoomType[roomType]) {
        byRoomType[roomType] = [];
      }
      byRoomType[roomType].push(analysis);
    });
    
    return {
      success: true,
      analyses,
      byRoomType,
    };
  } catch (error: any) {
    console.error('Batch image analysis error:', error.message);
    return {
      success: false,
      error: error.message || 'Failed to analyze images',
    };
  }
}

